### ISSUE TITLE
cloud formatation template error:	Encountered unsupported property VpcId

### ISSUE THREAD

**Issue by venkatmamillapalli** [QT-DevOps/AWSIssues#10]
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "Learing Cloudformation",
  "Resources": {
    "myvpcone": {
      "Type": "AWS::EC2::VPC",
      "Properties": {
        "CidrBlock": "10.0.0.0/16",
        "Tags": [
          {
            "Key": "name",
            "Value": "cloudformation"
          }
        ]
      }
    },
    "subweb": {
      "Type": "AWS::EC2::Subnet",
      "Properties": {
        "VpcId": {
          "Ref": "myvpcone"
        },
        "CidrBlock": "10.0.0.0/24",
        "Tags": [
          {
            "Key": "name",
            "Value": "public"
          }
        ]
      }
    },
    "websub": {
      "Type": "AWS::EC2::Subnet",
      "Properties": {
        "VpcId": {
          "Ref": "myvpcone"
        },
        "CidrBlock": "10.0.1.0/24",
        "Tags": [
          {
            "Key": "name",
            "Value": "private"
          }
        ]
      }
    },
    "myinstence": {
      "Type": "AWS::EC2::Instance",
      "Properties": {
        "KeyName": "lazy",
        "ImageId": "ami-0c55b159cbfafe1f0",
        "InstanceType": "t2.micro",
        "SecurityGroupIds": [
          "sg-0492d763bccebc22a"
        ],
        "VpcId": {
          "Ref": "myvpcone"
        },
        "SubnetId": {
          "Ref": "websub"
        },
        "Tags": [
          {
            "Key": "name",
            "Value": "ec2"
          }
        ],
        "UserData": {
          "Fn::Base64": {
            "Fn::Join": [
              "",
              [
                "#!/bin/bash -ex",
                "-"
              ]
            ]
          }
        }
      }
    }
  }
}

**Comment by venkatmamillapalli** [comment]
After completion of creating vpc and sub nets getting error like "encountered unsupported property VpcId"

**Comment by Abhishek010397** [comment]
as far as i can see to fetch the id of the vpc we use

"Type":  "AWS::EC2::VPC::Id"
and then refer this where we want to as per our needs.

Hope this works for you!
