### ISSUE TITLE
vagrant login issue

### ISSUE THREAD

**Issue by tabrez78** [QT-DevOps/AWSIssues#100]
sir created an ec2 instance using ami which i got after migration but cannot log into it even after giving the insecurefile path and user as vagrant

**Comment by srmanikanta** [comment]
tabrez please ensure user name and pem file or password, is it existed on ami what you created.
* first launch one machine and create a user and set password then install your required softwares if necessary.
* then add the user in visudo, and enable password authentication in /etc/ssh/sshd_config file
* restart the sshd service
* finnally create an image and then use that ami in your migration, after migration try to login into the machine using previously created user and password.

i think it might helpful if not please ignore.
