### ISSUE TITLE
Unable to create a subnet in the available zone

### ISSUE THREAD

**Issue by capgems** [QT-DevOps/AWSIssues#102]
Im getting the below error in the image can you please help me to resolve.

![image](https://user-images.githubusercontent.com/36443608/87384427-5857eb80-c5b9-11ea-9783-08be2d753bb1.png)
![image](https://user-images.githubusercontent.com/36443608/87384491-876e5d00-c5b9-11ea-8321-91095cc7989b.png)

**Comment by capgems** [comment]
Any update on this issue ?

**Comment by srmanikanta** [comment]
please check your region and changed to oregon region in the aws cli
