### ISSUE TITLE
cannot create a tag

### ISSUE THREAD

**Issue by tabrez78** [QT-DevOps/AWSIssues#103]
aws ec2 create-vpc --cidr-block 192.168.0.0/16 --tag-specifications 'ResourceType=vpc,Tags=[Key=Name,Value=cli-vpc]'

am i using the right syntax to create the tags or do i need to create a tag after creating a resource
Unknown options: --tag-specifications, ResourceType=vpc,Tags=[{Key=Name,Value=myvpc}]

**Comment by tabrez78** [comment]
aws ec2 create-vpc --cidr-block 192.168.0.0/16 --tag-specifications 'ResourceType=vpc,Tags=[Key=Name,Value=cli-vpc]'
even tried this command its not working

**Comment by ramjagadeeshkumar** [comment]
--tag-specifications (list) 
In list we can mention name
