### ISSUE TITLE
unable to connect to ubuntu server

### ISSUE THREAD

**Issue by Mouni-ops** [QT-DevOps/AWSIssues#104]
I have created EC2 ubuntu instance and while trying to access in git bash I am getting Port 22: connection refused error. Please help  me to get out from this issue.

Note: ssh,http and alltraffic  ports are added and enabled

**Comment by srmanikanta** [comment]
set source is anywhere and check the pem file path, mention a valid pem path.
Note: some times it will take time because still the  instance ckecks are passed.
