### ISSUE TITLE
Default apache webpage is not loading - with docker image

### ISSUE THREAD

**Issue by sharmilaOleti** [QT-DevOps/AWSIssues#109]
After pulling a new image of tomcat. the server does not start and the web page is not getting loaded.
The commands I have used 
docker pull tomcat
docker run -it --rm -p 8888:8080 tomcat:9.0
-------------------------------------------------------
![image](https://user-images.githubusercontent.com/36918359/99521067-f02b7300-29b9-11eb-8a99-0893febb3043.png)

**Comment by yagnasivasai** [comment]
Please tell us how do u solve?

**Comment by sharmilaOleti** [comment]
@yaznasivasai In my case, I have opened my host machine port which is 8888 previously I was trying to access the port which I have not opened.

See if this works for you!

**Comment by yagnasivasai** [comment]
Thank you..I got the same problem when I deployed mangodb application in minikube
