### ISSUE TITLE
EC2 public machine

### ISSUE THREAD

**Issue by muppidianuraag** [QT-DevOps/AWSIssues#11]
Is it always necessary to have the Internet gateway in place to ssh in to a public machine in EC2?

**Comment by ghost** [comment]
can you elaborate question

**Comment by sandhyadev** [comment]
For every vpc , Internet gateway  is must and  should.
To login to ec2 machine ssh port  open and attach your vpc to internet gateway.

**Comment by ghost** [comment]
please close if it resolve
