### ISSUE TITLE
AWS was not able to validate the provided access credentials

### ISSUE THREAD

**Issue by muppidianuraag** [QT-DevOps/AWSIssues#12]
i have configured my machine with latest aws credentials to use AWS CLI . But i get this error on my mac terminal when i run aws commands to create VPN. Do you know why this is happening and what i should do to fix this?

**Comment by sandhyadev** [comment]
pls share ur terminal sreenshot. let me knoe what exact issue u have.

**Comment by ghost** [comment]
please share logs

**Comment by sandhyadev** [comment]
Please respond muppidianuraag
