### ISSUE TITLE
Query on AWS RDS DB Instance creation

### ISSUE THREAD

**Issue by srinivle** [QT-DevOps/AWSIssues#13]
Hi Sir, good day, please find the output logs: 

Whenever I try to create a db instance using the below both the --db-security-groups & --vpc-security-group-ids is not taking . Below is the error:

PS C:\Users\Leela\Downloads\QualityThought_CloudCourses\Azure Material> aws rds create-db-instance --db-name mydb --db-instance-identi
fier mydb --allocated-storage 20 --db-instance-class db.t2.micro --engine mysql --master-username mydb --master-user-password Srinivas
881985 --db-security-groups mydbsecuritygroup --vpc-security-group-ids vpc-0054c8493b7a85ad4 --availability-zone us-east-1a --db-subne
t-group-name dbsubnet --port 3306

**An error occurred (InvalidParameterCombination) when calling the CreateDBInstance operation: DB Security Groups and Vpc Security Groups cannot both be provided.**

Also, if we give either of the one , below is the error : 

removing --db-security-groups & including --vpc-security-group-ids options

PS C:\Users\Leela\Downloads\QualityThought_CloudCourses\Azure Material> aws rds create-db-instance --db-name mydb --db-instance-identi
fier mydb --allocated-storage 20 --db-instance-class db.t2.micro --engine mysql --master-username mydb --master-user-password Srinivas
881985 --vpc-security-group-ids vpc-0054c8493b7a85ad4 --availability-zone us-east-1a --db-subnet-group-name dbsubnet --port 3306

**An error occurred (InvalidParameterValue) when calling the CreateDBInstance operation: Invalid security group , groupId= vpc-0054c8493b7a85ad4, groupName=.**

including   --db-security-groups & removing --vpc-security-group-ids options
PS C:\Users\Leela\Downloads\QualityThought_CloudCourses\Azure Material> aws rds create-db-instance --db-name mydb --db-instance-identi
fier mydb --allocated-storage 20 --db-instance-class db.t2.micro --engine mysql --master-username mydb --master-user-password Srinivas
881985 --db-security-groups mydbsecuritygroup --availability-zone us-east-1a --db-subnet-group-name dbsubnet --port 3306

**An error occurred (InvalidParameterCombination) when calling the CreateDBInstance operation: DB Security Groups can only be associated with VPC DB Instances using API versions 2012-01-15 through 2012-09-17.**

If I remove both the options , it worked fantastic and db instance created: 

PS C:\Users\Leela\Downloads\QualityThought_CloudCourses\Azure Material> aws rds create-db-instance --db-name mydb --db-instance-identi
fier mydb --allocated-storage 20 --db-instance-class db.t2.micro --engine mysql --master-username mydb --master-user-password Srinivas
881985 --availability-zone us-east-1a --db-subnet-group-name dbsubnet --port 3306

{
    "DBInstance": {
        "DBInstanceIdentifier": "mydb",
        "DBInstanceClass": "db.t2.micro",
        "Engine": "mysql",
        "DBInstanceStatus": "creating",
        "MasterUsername": "mydb",
        "DBName": "mydb",
        "AllocatedStorage": 20,
        "PreferredBackupWindow": "09:12-09:42",
        "BackupRetentionPeriod": 1,
        "DBSecurityGroups": [],
        "VpcSecurityGroups": [
            {
                "VpcSecurityGroupId": "sg-0418b8daa0c803488",
                "Status": "active"
            }
        ],
        "DBParameterGroups": [
            {
                "DBParameterGroupName": "default.mysql5.7",
                "ParameterApplyStatus": "in-sync"
            }
        ],
        "AvailabilityZone": "us-east-1a",
        "DBSubnetGroup": {
            "DBSubnetGroupName": "dbsubnet",
            "DBSubnetGroupDescription": "This is a DataBase Subnet",
            "VpcId": "vpc-0054c8493b7a85ad4",
            "SubnetGroupStatus": "Complete",
            "Subnets": [
                {
                    "SubnetIdentifier": "subnet-0e596165ae4ff90dc",
                    "SubnetAvailabilityZone": {
                        "Name": "us-east-1b"
                    },
                    "SubnetStatus": "Active"
                },
                {
                    "SubnetIdentifier": "subnet-0442ab17f3ef0421a",
                    "SubnetAvailabilityZone": {
                        "Name": "us-east-1a"
                    },
                    "SubnetStatus": "Active"
                }
            ]
        },
        "PreferredMaintenanceWindow": "fri:10:21-fri:10:51",
        "PendingModifiedValues": {
            "MasterUserPassword": "****"
        },
        "MultiAZ": false,
        "EngineVersion": "5.7.22",
        "AutoMinorVersionUpgrade": true,
        "ReadReplicaDBInstanceIdentifiers": [],
        "LicenseModel": "general-public-license",
        "OptionGroupMemberships": [
            {
                "OptionGroupName": "default:mysql-5-7",
                "Status": "in-sync"
            }
        ],
        "PubliclyAccessible": false,
        "StorageType": "gp2",
        "DbInstancePort": 0,
        "StorageEncrypted": false,
        "DbiResourceId": "db-UP4KSFUKQMFJNFCQIT6PASSHVI",
        "CACertificateIdentifier": "rds-ca-2015",
        "DomainMemberships": [],
        "CopyTagsToSnapshot": false,
        "MonitoringInterval": 0,
        "DBInstanceArn": "arn:aws:rds:us-east-1:713051151333:db:mydb",
        "IAMDatabaseAuthenticationEnabled": false,
        "PerformanceInsightsEnabled": false,
        "DeletionProtection": false,
        "AssociatedRoles": []
    }
}

Also, when I create the create-db-security-group command it is taking the default vpc but not the one which I created ..... 
Without giving the options of --db-security-groups & --vpc-security-group-ids , it worked well and DB instance created fine in AWS RDS. Then, may i know the need or reason for these options when it is taking default value instead of our own VPC ???? 
Could you please explain why this has happened??? 

Hope you got my point. Sir, Kindly check and let me know please sir !!!

**Comment by ghost** [comment]
An error occurred (InvalidParameterValue) when calling the CreateDBInstance operation: Invalid security group , groupId= vpc-0054c8493b7a85ad4, groupN
##########################################
please provide security group id not vpc-id

**Comment by srinivle** [comment]
> An error occurred (InvalidParameterValue) when calling the CreateDBInstance operation: Invalid security group , groupId= vpc-0054c8493b7a85ad4, groupN
> ##########################################
> please provide security group id not vpc-id

sir, It looks like you haven't read my message correctly..... It worked when I dont give both the options .... If I give either one of the options , it is failing for sure..... It looks like "--db-security-groups" option is not necessary to provide while creating the db instance ... !!!

**Comment by ghost** [comment]
without providing a security group and subnet we can  create rds but it created in default vpc

**Comment by srinivle** [comment]
> without providing a security group we can create rds but no use, we can't access

Ohh okay..... Sir, we shall do webex and discuss and work upon !!! ... Thank you very much sir...

**Comment by ghost** [comment]
hi srinivle 
I think you got an idea of your issue 
if it's done 
close your issue

**Comment by srinivle** [comment]
> hi srinivle
> I think you got an idea of your issue
> if it's done
> close your issue

Got it Naresh garu.... Thank you very much for all your help and support as always. We shall get in touch and perhaps you know and remember me... !

**Comment by ghost** [comment]
please close issue
