### ISSUE TITLE
creating RDS Data base Read Replica error

### ISSUE THREAD

**Issue by SatishChandra100** [QT-DevOps/AWSIssues#14]
An instance of type db.t2.micro can't be a primary for the oracle-ee engine.
 (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: b5cffb45-8f74-41de-ac1a-fde6d47bfa62)

**Comment by sandhyadev** [comment]
db.t2.micro is not work for oracle-ee engine.
db.m5.large is work for oracle Enterprise Edition engine

**Comment by ghost** [comment]
use MySQL

**Comment by SatishChandra100** [comment]
yes worked for MySQL....thanks!!

**Comment by ghost** [comment]
close issue
