### ISSUE TITLE
Error while creating read replica

### ISSUE THREAD

**Issue by muppidianuraag** [QT-DevOps/AWSIssues#16]
Anuraags-MacBook-Pro:~ anuraagmuppidi$ aws rds create-db-instance-read-replica --db-instance-identifier anuraag-rds-mysql-learning-replica --source-db-instance-identifier anuraag-rds-mysql-learning --availability-zone us-west-2c --port 3306 --publicly-accessible 

An error occurred (InvalidDBInstanceState) when calling the CreateDBInstanceReadReplica operation: Automated backups are not enabled for this database instance. To enable automated backups, use ModifyDBInstance to set the backup retention period to a non-zero value.

**Comment by ghost** [comment]
give the value non-zero for this (--backup-retention-period)
-----------------------------------------------------------------------------
The number of days for which automated backups are retained. Setting this parameter to a positive number enables backups

**Comment by AnandSag** [comment]
I found below constrains for creating read replica.(https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-instance-read-replica.html)

--source-db-instance-identifier (string)

The identifier of the DB instance that will act as the source for the Read Replica. Each DB instance can have up to five Read Replicas.

Constraints:

Must be the identifier of an existing MySQL, MariaDB, Oracle, or PostgreSQL DB instance.
Can specify a DB instance that is a MySQL Read Replica only if the source is running MySQL 5.6 or later.
For the limitations of Oracle Read Replicas, see Read Replica Limitations with Oracle in the Amazon RDS User Guide .
Can specify a DB instance that is a PostgreSQL DB instance only if the source is running PostgreSQL 9.3.5 or later (9.4.7 and higher for cross-region replication).
**The specified DB instance must have automatic backups enabled, its backup retention period must be greater than 0.**
If the source DB instance is in the same AWS Region as the Read Replica, specify a valid DB instance identifier.
If the source DB instance is in a different AWS Region than the Read Replica, specify a valid DB instance ARN. For more information, go to Constructing an ARN for Amazon RDS in the Amazon RDS User Guide .


Enable auto-backup  for DB cluster and try to create read replica
