### ISSUE TITLE
Regarding Subnets

### ISSUE THREAD

**Issue by khatrigopal** [QT-DevOps/AWSIssues#17]
In My existing VPC there are 8 subnets so how can i found which is in Private subnet or which are in Public subnet.

**Comment by ghost** [comment]
one way is based on the route table
-----------------------------------------------------------------------
PUBLIC SUBNET If a subnet's traffic is routed to an internet gateway, the subnet is known as a public subnet. PRIVATE SUBNET If a subnet doesn't have a route to the internet gateway, the subnet is known as a private subnet.

**Comment by sandhyadev** [comment]
You can found which one is  Private subnet & which one is Public subnet by using 'route' in the route table.

A private subnet sets the internet traffic , route to a NAT instance. Private subnet instances only need a private ip and internet traffic is routed through the NAT in the public subnet. 

A public subnet routes 0.0.0.0/0 through an Internet Gateway (igw). Instances in a public subnet require public IPs to talk to the internet.

**Comment by khatrigopal** [comment]
Done

**Comment by khatrigopal** [comment]
Done
