### ISSUE TITLE
Unable to mount the EFS volume :::: Khaja Sir is once again AWESOME And GREAT Sir ji .... (Salaam ji)

### ISSUE THREAD

**Issue by srinivle** [QT-DevOps/AWSIssues#18]
root@ip-192-168-1-134:/# ls -ltr | grep -i efs
drwxr-xr-x   2 root root  4096 Jun  8 03:12 efs
root@ip-192-168-1-134:/# lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
xvda    202:0    0    8G  0 disk
└─xvda1 202:1    0    8G  0 part /
loop0     7:0    0 88.4M  1 loop /snap/core/6964
loop1     7:1    0 89.4M  1 loop /snap/core/6818
loop2     7:2    0   18M  1 loop /snap/amazon-ssm-agent/1335
root@ip-192-168-1-134:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            488M     0  488M   0% /dev
tmpfs           100M  3.3M   96M   4% /run
/dev/xvda1      7.7G  3.1G  4.7G  40% /
tmpfs           496M     0  496M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           496M     0  496M   0% /sys/fs/cgroup
/dev/loop0       89M   89M     0 100% /snap/core/6964
/dev/loop1       90M   90M     0 100% /snap/core/6818
/dev/loop2       18M   18M     0 100% /snap/amazon-ssm-agent/1335
tmpfs           100M     0  100M   0% /run/user/1000
root@ip-192-168-1-134:/# mount -t efs fs-c45bc227:/ /efs
mount: unknown filesystem type 'efs'
root@ip-192-168-1-134:/# mount -t efs fs-c45bc227:/ /mnt/efs
mount: mount point /mnt/efs does not exist
root@ip-192-168-1-134:/# mount -t efs fs-c45bc227:/ efs
mount: unknown filesystem type 'efs'
root@ip-192-168-1-134:/#

**Comment by srinivle** [comment]
This is the same security group & subnet & VPC is used for the same EC2 instance & EFS volume :::::: 

![image](https://user-images.githubusercontent.com/50224645/59141848-c18e2800-89d1-11e9-929e-2452b9524716.png)

![image](https://user-images.githubusercontent.com/50224645/59141863-01550f80-89d2-11e9-920e-bd17abd63224.png)

![image](https://user-images.githubusercontent.com/50224645/59141871-26498280-89d2-11e9-8666-82e74429dcbe.png)

**Comment by srinivle** [comment]
Kindly check and help me out !!!

**Comment by srinivle** [comment]
Also, by the way, how can I identify my efs volume in ec2 instance when it is mounted or do a command of lsblk ???

**Comment by srinivle** [comment]
It worked after thorough checking. Simply executing the command from "Amazon EC2 mount instructions (from local VPC)" from "AWS EFS Console after creation of EFS volume", it will not work. We need to follow the below steps one after another and then only it will work. This is especially for Ubuntu machine !!! 

root@ip-192-168-1-134:/# apt-get install git -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
git is already the newest version (1:2.7.4-0ubuntu1.6).
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.
root@ip-192-168-1-134:/# git clone https://github.com/aws/efs-utils
Cloning into 'efs-utils'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 235 (delta 13), reused 35 (delta 12), pack-reused 191
Receiving objects: 100% (235/235), 77.75 KiB | 0 bytes/s, done.
Resolving deltas: 100% (90/90), done.
Checking connectivity... done.

root@ip-192-168-1-134:/# apt-get install make
Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  make-doc
The following NEW packages will be installed:
  make
0 upgraded, 1 newly installed, 0 to remove and 24 not upgraded.
Need to get 151 kB of archives.
After this operation, 365 kB of additional disk space will be used.
Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial/main amd64 make amd64 4.1-6 [151 kB]
Fetched 151 kB in 0s (11.5 MB/s)
Selecting previously unselected package make.
(Reading database ... 77664 files and directories currently installed.)
Preparing to unpack .../archives/make_4.1-6_amd64.deb ...
Unpacking make (4.1-6) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up make (4.1-6) ...

root@ip-192-168-1-134:/# apt-get install binutils -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  binutils-doc
The following NEW packages will be installed:
  binutils
0 upgraded, 1 newly installed, 0 to remove and 24 not upgraded.
Need to get 2,312 kB of archives.
After this operation, 13.7 MB of additional disk space will be used.
Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 binutils amd64 2.26.1-1ubuntu1~16.04.8 [2,312 kB]
Fetched 2,312 kB in 0s (28.6 MB/s)
Selecting previously unselected package binutils.
(Reading database ... 77680 files and directories currently installed.)
Preparing to unpack .../binutils_2.26.1-1ubuntu1~16.04.8_amd64.deb ...
Unpacking binutils (2.26.1-1ubuntu1~16.04.8) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up binutils (2.26.1-1ubuntu1~16.04.8) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
root@ip-192-168-1-134:/#

root@ip-192-168-1-134:/efs-utils# ./build-deb.sh
+ pwd
+ BASE_DIR=/efs-utils
+ BUILD_ROOT=/efs-utils/build/debbuild
+ VERSION=1.7
+ echo Cleaning deb build workspace
Cleaning deb build workspace
+ rm -rf /efs-utils/build/debbuild
+ mkdir -p /efs-utils/build/debbuild
+ echo Creating application directories
Creating application directories
+ mkdir -p /efs-utils/build/debbuild/etc/amazon/efs
+ mkdir -p /efs-utils/build/debbuild/etc/init/
+ mkdir -p /efs-utils/build/debbuild/etc/systemd/system
+ mkdir -p /efs-utils/build/debbuild/sbin
+ mkdir -p /efs-utils/build/debbuild/usr/bin
+ mkdir -p /efs-utils/build/debbuild/var/log/amazon/efs
+ mkdir -p /efs-utils/build/debbuild/usr/share/man/man8
+ echo Copying application files
Copying application files
+ install -p -m 644 dist/amazon-efs-mount-watchdog.conf /efs-utils/build/debbuild/etc/init
+ install -p -m 644 dist/amazon-efs-mount-watchdog.service /efs-utils/build/debbuild/etc/systemd/system
+ install -p -m 444 dist/efs-utils.crt /efs-utils/build/debbuild/etc/amazon/efs
+ install -p -m 644 dist/efs-utils.conf /efs-utils/build/debbuild/etc/amazon/efs
+ install -p -m 755 src/mount_efs/__init__.py /efs-utils/build/debbuild/sbin/mount.efs
+ install -p -m 755 src/watchdog/__init__.py /efs-utils/build/debbuild/usr/bin/amazon-efs-mount-watchdog
+ echo Copying install scripts
Copying install scripts
+ install -p -m 755 dist/scriptlets/after-install-upgrade /efs-utils/build/debbuild/postinst
+ install -p -m 755 dist/scriptlets/before-remove /efs-utils/build/debbuild/prerm
+ install -p -m 755 dist/scriptlets/after-remove /efs-utils/build/debbuild/postrm
+ echo Copying control file
Copying control file
+ install -p -m 644 dist/amazon-efs-utils.control /efs-utils/build/debbuild/control
+ echo Copying conffiles
Copying conffiles
+ install -p -m 644 dist/amazon-efs-utils.conffiles /efs-utils/build/debbuild/conffiles
+ echo Copying manpages
Copying manpages
+ install -p -m 644 man/mount.efs.8 /efs-utils/build/debbuild/usr/share/man/man8/mount.efs.8
+ echo Creating deb binary file
Creating deb binary file
+ echo 2.0
+ echo Setting permissions
Setting permissions
+ xargs chmod 755
+ find /efs-utils/build/debbuild -type d
+ echo Creating tar
Creating tar
+ cd /efs-utils/build/debbuild
+ tar czf control.tar.gz control conffiles postinst prerm postrm --owner=0 --group=0
+ tar czf data.tar.gz etc sbin usr var --owner=0 --group=0
+ cd /efs-utils
+ echo Building deb
Building deb
+ DEB=/efs-utils/build/debbuild/amazon-efs-utils-1.7-1.deb
+ ar r /efs-utils/build/debbuild/amazon-efs-utils-1.7-1.deb /efs-utils/build/debbuild/debian-binary
ar: creating /efs-utils/build/debbuild/amazon-efs-utils-1.7-1.deb
+ ar r /efs-utils/build/debbuild/amazon-efs-utils-1.7-1.deb /efs-utils/build/debbuild/control.tar.gz
+ ar r /efs-utils/build/debbuild/amazon-efs-utils-1.7-1.deb /efs-utils/build/debbuild/data.tar.gz
+ echo Copying deb to output directory
Copying deb to output directory
+ cp /efs-utils/build/debbuild/amazon-efs-utils-1.7-1.deb build/
root@ip-192-168-1-134:/efs-utils# apt-get -y install ./build/amazon-efs-utils*deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'amazon-efs-utils' instead of './build/amazon-efs-utils-1.7-1.deb'
The following additional packages will be installed:
  stunnel4
Suggested packages:
  logcheck-database
The following NEW packages will be installed:
  amazon-efs-utils stunnel4
0 upgraded, 2 newly installed, 0 to remove and 24 not upgraded.
Need to get 146 kB/162 kB of archives.
After this operation, 432 kB of additional disk space will be used.
Get:1 /efs-utils/build/amazon-efs-utils-1.7-1.deb amazon-efs-utils all 1.7 [15.1 kB]
Get:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 stunnel4 amd64 3:5.30-1ubuntu0.1 [146 kB]
Fetched 146 kB in 0s (2,711 kB/s)
Selecting previously unselected package stunnel4.
(Reading database ... 77889 files and directories currently installed.)
Preparing to unpack .../stunnel4_3%3a5.30-1ubuntu0.1_amd64.deb ...
Unpacking stunnel4 (3:5.30-1ubuntu0.1) ...
Selecting previously unselected package amazon-efs-utils.
Preparing to unpack .../amazon-efs-utils-1.7-1.deb ...
Unpacking amazon-efs-utils (1.7) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for ureadahead (0.100.0-19.1) ...
Processing triggers for systemd (229-4ubuntu21.21) ...
Setting up stunnel4 (3:5.30-1ubuntu0.1) ...
Warning: The home dir /var/run/stunnel4 you specified can't be accessed: No such file or directory
Adding system user `stunnel4' (UID 113) ...
Adding new group `stunnel4' (GID 116) ...
Adding new user `stunnel4' (UID 113) with group `stunnel4' ...
Not creating home directory `/var/run/stunnel4'.
Setting up amazon-efs-utils (1.7) ...
Processing triggers for ureadahead (0.100.0-19.1) ...
Processing triggers for systemd (229-4ubuntu21.21) ...
root@ip-192-168-1-134:/efs-utils# sudo mount -t efs fs-c45bc227:/ efs
mount.nfs4: mount point efs does not exist
root@ip-192-168-1-134:/efs-utils# cd /
root@ip-192-168-1-134:/# sudo mount -t efs fs-c45bc227:/ efs
root@ip-192-168-1-134:/# df -h
Filesystem                                 Size  Used Avail Use% Mounted on
udev                                       488M     0  488M   0% /dev
tmpfs                                      100M  3.3M   96M   4% /run
/dev/xvda1                                 7.7G  3.1G  4.7G  40% /
tmpfs                                      496M     0  496M   0% /dev/shm
tmpfs                                      5.0M     0  5.0M   0% /run/lock
tmpfs                                      496M     0  496M   0% /sys/fs/cgroup
/dev/loop0                                  89M   89M     0 100% /snap/core/6964
/dev/loop1                                  90M   90M     0 100% /snap/core/6818
/dev/loop2                                  18M   18M     0 100% /snap/amazon-ssm-agent/1335
tmpfs                                      100M     0  100M   0% /run/user/1000
fs-c45bc227.efs.us-east-1.amazonaws.com:/  8.0E     0  8.0E   0% /efs
root@ip-192-168-1-134:/#

root@ip-192-168-1-134:/# lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
xvda    202:0    0    8G  0 disk
└─xvda1 202:1    0    8G  0 part /
loop0     7:0    0 88.4M  1 loop /snap/core/6964
loop1     7:1    0 89.4M  1 loop /snap/core/6818
loop2     7:2    0   18M  1 loop /snap/amazon-ssm-agent/1335
root@ip-192-168-1-134:/#

Successfully able to mount the EFS volume to my EC2 instance system. Thank you Sir .

**Comment by chowdamramana** [comment]
> root@ip-192-168-1-134:/# ls -ltr | grep -i efs
> drwxr-xr-x 2 root root 4096 Jun 8 03:12 efs
> root@ip-192-168-1-134:/# lsblk
> NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
> xvda 202:0 0 8G 0 disk
> └─xvda1 202:1 0 8G 0 part /
> loop0 7:0 0 88.4M 1 loop /snap/core/6964
> loop1 7:1 0 89.4M 1 loop /snap/core/6818
> loop2 7:2 0 18M 1 loop /snap/amazon-ssm-agent/1335
> root@ip-192-168-1-134:/# df -h
> Filesystem Size Used Avail Use% Mounted on
> udev 488M 0 488M 0% /dev
> tmpfs 100M 3.3M 96M 4% /run
> /dev/xvda1 7.7G 3.1G 4.7G 40% /
> tmpfs 496M 0 496M 0% /dev/shm
> tmpfs 5.0M 0 5.0M 0% /run/lock
> tmpfs 496M 0 496M 0% /sys/fs/cgroup
> /dev/loop0 89M 89M 0 100% /snap/core/6964
> /dev/loop1 90M 90M 0 100% /snap/core/6818
> /dev/loop2 18M 18M 0 100% /snap/amazon-ssm-agent/1335
> tmpfs 100M 0 100M 0% /run/user/1000
> root@ip-192-168-1-134:/# mount -t efs fs-c45bc227:/ /efs
> mount: unknown filesystem type 'efs'
> root@ip-192-168-1-134:/# mount -t efs fs-c45bc227:/ /mnt/efs
> mount: mount point /mnt/efs does not exist
> root@ip-192-168-1-134:/# mount -t efs fs-c45bc227:/ efs
> mount: unknown filesystem type 'efs'
> root@ip-192-168-1-134:/#

can you please tell me the solution for this problem
