### ISSUE TITLE
aws cli 

### ISSUE THREAD

**Issue by amit2793** [QT-DevOps/AWSIssues#25]
hey
i need help with these topics. Can i get commands to execute

1)how to do network interfacing in aws using cli
2)how to create security groups using cli
3) how to do autoscaling and load balancing in aws using cli

Please help....

**Comment by ghost** [comment]
aws ec2 create-network-interface --subnet-id subnet-9d4a7b6c --description "my network interface" --groups sg-903004f8 --private-ip-address 10.0.2.17   
create security group 
aws ec2 create-security-group --group-name MySecurityGroup --description "My security group"
https://docs.aws.amazon.com/cli/latest/reference/ec2/authorize-security-group-egress.html#examples --To add a rule that allows outbound traffic to a specific address range
----
load balancer
-----------------------------
https://docs.aws.amazon.com/cli/latest/reference/elb/index.html#cli-aws-elb
---------------------------------

**Comment by amit2793** [comment]
hi,Naresh

can you tell me basic autoscaling and load balancing commands, i mean how to execute.?

thanks for previous help.
