### ISSUE TITLE
Question related to Azure to AWS migration 

### ISSUE THREAD

**Issue by jayshah7** [QT-DevOps/AWSIssues#27]
Hello all, 

After attending todays AWS migration class, I was trying to migrate from Azure to AWS using below Powershell script : 
.\aws-sms-azure-setup.ps1 -StorageAccountName name -ExistingVNetName name -SubscriptionId id -SubnetName name

But at the end of the script it fails saying failed to create connector virtual machine as the limit of CPU core have exceeded, with 3 in use and need 4 more cores. ****I want the script to skip the step to create connector VM or how can we add CPU core quote as it is saying free account cannot increase core quota which is 4 currently.**** 

Please help as I am stuck here.

**Comment by ghost** [comment]
Free tier support t create only 4 Core CPU 
when you create a connector  creating VM with 4 core cpu 
if you want to do 
update to Pas-as-you-go  Subscription (limit is Upto 10 CPU's)

**Comment by jayshah7** [comment]
thanks, updated to Pay as you go !!!
