### ISSUE TITLE
Azure Connector getting Issue

### ISSUE THREAD

**Issue by sachin492** [QT-DevOps/AWSIssues#28]
Azure Connector getting issue. Please suggest on this

![image](https://user-images.githubusercontent.com/53104614/61574204-cb7b6e80-aad9-11e9-92b0-49d59498508c.png
[AWS_Migration.docx](https://github.com/QT-DevOps/AWSIssues/files/3413243/AWS_Migration.docx)
)

**Comment by ghost** [comment]
Free tier support t create only 4 Core CPU
when you create a connector creating VM with 4 core cpu
if you want to do
update to Pas-as-you-go Subscription (limit is Upto 10 CPU's)

**Comment by sachin492** [comment]
Hi Naresh, 

did u install on higher machine configuration.Please suggest configuration i dont want to be charged ot much.

Thanks,
sachin

**Comment by ghost** [comment]
sorry
no alternatives
