### ISSUE TITLE
Importing a VM as an Image Using VM Import/Export 

### ISSUE THREAD

**Issue by sachin492** [QT-DevOps/AWSIssues#29]
Not able to use the aws power shell to vm/import no command is working.

![image](https://user-images.githubusercontent.com/53104614/61613545-3dd98380-ac7f-11e9-8984-2bb88b192c49.png)

**Comment by sachin492** [comment]
[AWS_VMWARE_IMPORT.docx](https://github.com/QT-DevOps/AWSIssues/files/3416147/AWS_VMWARE_IMPORT.docx)

**Comment by ghost** [comment]
before run aws configure command you need to install aws-cli
