### ISSUE TITLE
error when mounting the efs 

### ISSUE THREAD

**Issue by chowdamramana** [QT-DevOps/AWSIssues#32]

**Comment by chowdamramana** [comment]
![Capture](https://user-images.githubusercontent.com/50665358/62763033-2fc19a80-baa8-11e9-97cd-2964f8e98995.PNG)
I am open all ports in ports in security group and also I am open the NFS port

**Comment by chowdamramana** [comment]
my mounting folder is efs
earlier I have tried with other directories also, but I got the same  error

**Comment by ghost** [comment]
please open ports
that security attach to efs

**Comment by chowdamramana** [comment]
> please open ports
> that security attach to efs

I have opened all the ports and also opened the NFS port, but it didn't workout

**Comment by sandhyadev** [comment]
please follow this link this might help you
Installing the amazon-efs-utils Package on Amazon Linux:
https://docs.aws.amazon.com/efs/latest/ug/using-amazon-efs-utils.html
Mount the Amazon EFS File System on the EC2 Instance and Test:
https://docs.aws.amazon.com/efs/latest/ug/wt1-test.html
