### ISSUE TITLE
Unable to create read replica in other region availability zone.

### ISSUE THREAD

**Issue by AnandSag** [QT-DevOps/AWSIssues#35]
Command:

aws rds create-db-instance-read-replica --db-instance-identifier "qt-rds-from-cli-read-only" --source-db-instance-identifier "qt-rds-from-cli" --db-instance-class "db.t2.micro" --availability-zone "ap-south-1a"

source DB is in us-west-2b

Error:  An error occurred (InvalidParameterValue) when calling the CreateDBInstanceReadReplica operation: ap-south-1a is not a valid availability zone.

**Comment by srmanikanta** [comment]
--source-db-instance-identifier name and --db-instance-identifier(in your database) name must be same and also availability zone

**Comment by AnandSag** [comment]
I can able to create a cross region read replica from console with different db-instance name.

**Comment by ghost** [comment]
try some other region (az)
