### ISSUE TITLE
vagrant up

### ISSUE THREAD

**Issue by navaneethmola** [QT-DevOps/AWSIssues#4]
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
PS F:\VAGRANT\jenkins> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/xenial64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "677aba1b-8749-448e-b9a2-1bb621151283", "--type", "headless"]

Stderr: VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
PS F:\VAGRANT\jenkins>

**Comment by anon-42** [comment]
If you OS is Windows 8/10 pro or higher version, Use hyper-V . Else go and disable HYPER-V in _windows features_  for using virtualbox , reboot. And try again

**Comment by shaikkhajaibrahim** [comment]
https://stackoverflow.com/questions/37955942/vagrant-up-vboxmanage-exe-error-vt-x-is-not-available-verr-vmx-no-vmx-code

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by navaneethmola** [comment]
Thank you sir!!
