### ISSUE TITLE
i am getting command not found in new ubuntu 18.04 server 

### ISSUE THREAD

**Issue by chowdamramana** [QT-DevOps/AWSIssues#42]
![Capture](https://user-images.githubusercontent.com/50665358/66396207-e1bd0a80-e9f6-11e9-861b-37bb8fb5361e.PNG)

**Comment by chowdamramana** [comment]
I was tried with snap also ..getting the same error

**Comment by DevOpsEnz** [comment]
Aa per your screenshot, you are not using Ubuntu, its looks like a SUSE Linux, try use below command to update the patch

sudo zypper update

Thanks
DevOpsEnz

**Comment by chowdamramana** [comment]
> Aa per your screenshot, you are not using Ubuntu, its looks like a SUSE Linux, try use below command to update the patch
> 
> sudo zypper update
> 
> Thanks
> DevOpsEnz

it is ubuntu 18.04 zypper used as a package, iam unable to install java.
try your self with ubuntu now in aws
