### ISSUE TITLE
AWS and poweshell 

### ISSUE THREAD

**Issue by AsrithaSrikakolapu** [QT-DevOps/AWSIssues#43]
I got these errors when I tried to install git and awscli through powershell. But, when I tried to install them manually, they worked. Again, when I tried to access the IAM user from powershell, I got these error, when I tried it in another laptop, it worked.

Can you please suggest me what the problem is?
![IMG_20191026_131718](https://user-images.githubusercontent.com/57030731/67616261-8f684180-f78b-11e9-9cf5-ad2e406231af.JPG)
![IMG_20191026_131641 (1)](https://user-images.githubusercontent.com/57030731/67616262-9000d800-f78b-11e9-838f-2994be753f6f.JPG)
![IMG_20191026_131626](https://user-images.githubusercontent.com/57030731/67616353-5aa8ba00-f78c-11e9-9438-81d29bbad8b8.JPG)

**Comment by raviops99** [comment]
Hi Saritha,
Can you please post the which chocolatey and git versions you are trying to install

**Comment by raviops99** [comment]
Hi ashrita,
Choco install git -y
Please execute the commnad from command prompt 
I feel it is choclety software version issue
Try to install choclety any other version

**Comment by raviops99** [comment]
2. Regarding AWS cli issue
The error i guess you are creating iam user in one region your launching AWS instance in another region
Please create one more IAM user and try for same region

**Comment by raviops99** [comment]
Hi ashrita,
Is it chocolatey software version issue

**Comment by AsrithaSrikakolapu** [comment]
Hi
I think so. Previously I used Ram 2gb, windows 7 and Powershell version 4.
When I tried to update them individually, problem still remained the same.
So, I have added extra 4gb Ram, upgraded to windows 10 and I got default
Powershell version 5. And now it works fine. I was unable to find exactly
what the problem was.

Thanks for your help
Asritha
