### ISSUE TITLE
Apt-get update issue 

### ISSUE THREAD

**Issue by ashok655** [QT-DevOps/AWSIssues#44]
tryig to update ubunut 18 server but it is failing to update.Machine is created in VPC with NACL & security configured.

This is the error

Err:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic InRelease
  Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (54.218.137.160), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (34.210.25.51), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (34.212.136.213), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (54.190.18.91), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (54.191.55.41), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (54.191.70.203), connection timed out
Err:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease
  Unable to connect to us-west-2.ec2.archive.ubuntu.com:http:
Err:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease
  Unable to connect to us-west-2.ec2.archive.ubuntu.com:http:
Err:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::17). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::21). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1560:8001::11). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::16). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::19). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.91.23), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.24), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.26), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.24), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.31), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.149), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.162), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.173), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.174), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.14), connection timed out
Reading package lists... Done
W: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (54.218.137.160), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (34.210.25.51), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (34.212.136.213), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (54.190.18.91), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (54.191.55.41), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (54.191.70.203), connection timed out
W: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Unable to connect to us-west-2.ec2.archive.ubuntu.com:http:
W: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Unable to connect to us-west-2.ec2.archive.ubuntu.com:http:
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::17). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::21). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1560:8001::11). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::16). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::19). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.91.23), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.24), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.26), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.24), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.31), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.149), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.162), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.173), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.174), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.14), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
root@ip-10-10-1-114:/# apt-get update -y
Err:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic InRelease
  Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (54.218.137.160), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (34.210.25.51), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (34.212.136.213), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (54.190.18.91), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (54.191.55.41), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (54.191.70.203), connection timed out
Err:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease
  Unable to connect to us-west-2.ec2.archive.ubuntu.com:http:
Err:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease
  Unable to connect to us-west-2.ec2.archive.ubuntu.com:http:
Err:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1560:8001::11). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::16). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::19). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::17). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::21). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.88.31), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.149), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.162), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.173), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.174), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.14), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.23), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.24), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.26), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.24), connection timed out
Reading package lists... Done
W: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (54.218.137.160), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (34.210.25.51), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (34.212.136.213), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (54.190.18.91), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (54.191.55.41), connection timed out Could not connect to us-west-2.ec2.archive.ubuntu.com:80 (54.191.70.203), connection timed out
W: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Unable to connect to us-west-2.ec2.archive.ubuntu.com:http:
W: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Unable to connect to us-west-2.ec2.archive.ubuntu.com:http:
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1560:8001::11). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::16). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::19). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::17). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::21). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.88.31), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.149), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.162), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.173), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.174), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.14), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.23), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.24), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.26), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.24), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.

Is it something do with the protocal

**Comment by raviops99** [comment]
Hi Ashok,
Please find below link it may help
https://stackoverflow.com/questions/22955682/ec2-instance-on-aws-apt-get-not-working

**Comment by AsrithaSrikakolapu** [comment]
Hi,
Even I got the same issue. I have gone through the link you provided here. But, it didn't help me in any way. So, I have created flow logs for VPC. It is as follows(It is working only all traffic is allowed for inbound, but rejecting when give only the ssh rules). Kindly check them and help me with this.
[logs.txt](https://github.com/QT-DevOps/AWSIssues/files/3818129/logs.txt)

**Comment by shaikkhajaibrahim** [comment]
Can you share your network Creation script or commands or iamge

**Comment by AsrithaSrikakolapu** [comment]
HI Khaja Sir

my NACL rule which I gave 

Inbound - allow - http- 80
                  https- 443
		  ssh - 22

Outbound - All traffic - allow

Security group-
Inbound - allow - Http- 80
                  https- 443
		  ssh - 22
				   
the instance could be load 0 - package even though it's having internet.

Please help me to get packages for instance.

As per your task, given on date: 27-10-19, we were asked to create NACL with the inbound rule which allows ssh only. But, it is not working if we do so. It is working only if we give all TCP for NACL(inbound).

Please suggest me.

**Comment by AnandSag** [comment]
Seems your machine has no access to Internet. Please check your IGW is associated with the subnet and check the routes in the route table.

If the machine is running in private subnet. Please have a NAT gateway associated to it
