### ISSUE TITLE
Problem with login to EC2 Instance through Gitbash

### ISSUE THREAD

**Issue by ishashi7** [QT-DevOps/AWSIssues#46]
![Capture](https://user-images.githubusercontent.com/36628286/68845168-017bd880-06f1-11ea-81b2-67cfb6a230ac.JPG)

**Comment by srmanikanta** [comment]
please follow the below steps:
1. your ec2ex.pem file is in downloads path 
2. check security group if ssh 22 is allow or not
3. check the machine is running if it is running please take the correct ssh id
I hope this is useful to you if not please ignore
Note: if you run your machine with a default vpc noproblem but if you run your machine with custom vpc please check once your vpc is configure correctly or not
if you find the solution to this please close the issue
