### ISSUE TITLE
not installing aws cli in windows

### ISSUE THREAD

**Issue by Rupini93** [QT-DevOps/AWSIssues#47]

**Comment by Rupini93** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/57709400/68930751-11f58700-07b5-11ea-8ce9-e44e73672670.png)

**Comment by srmanikanta** [comment]
Follow the below link 
https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-windows.html#cliv2-windows-install
aws2 --version is cli version 2 and the command is aws2 in future releases the comnmand might be change. 
please close the issue if it is solved
