### ISSUE TITLE
i cant understand why i am getting permission denied. i have given public instance id.

### ISSUE THREAD

**Issue by Rupini93** [QT-DevOps/AWSIssues#48]
![Screenshot (7)](https://user-images.githubusercontent.com/57709400/68954715-957d9b00-07ea-11ea-8393-756827a8f5de.png)

**Comment by raviops99** [comment]
Hi rupini,
Just add sudo before the command
Ex: sudo ssh - i ec2learning.pem ubuntu@ip

**Comment by Abbanapuri** [comment]
please verify  pem file and vpc subnet route table sg nacl
