### ISSUE TITLE
Virtual Box could not able to install

### ISSUE THREAD

**Issue by RajPraveen123** [QT-DevOps/AWSIssues#5]
PS C:\Users\MADHAN MOHAN REDDY> choco install virtualbox  -y
Chocolatey v0.10.13
2 validations performed. 1 success(es), 1 warning(s), and 0 error(s).

Validation Warnings:
 - A pending system reboot request has been detected, however, this is
   being ignored due to the current Chocolatey configuration.  If you
   want to halt when this occurs, then either set the global feature
   using:
     choco feature enable -name=exitOnRebootDetected
   or pass the option --exit-when-reboot-detected.

Chocolatey detected you are not running from an elevated command shell
 (cmd/powershell).

 You may experience errors - many functions/packages
 require admin rights. Only advanced users should run choco w/out an
 elevated shell. When you open the command shell, you should ensure
 that you do so with "Run as Administrator" selected. If you are
 attempting to use Chocolatey in a non-administrator setting, you
 must select a different location other than the default install
 location. See
 https://chocolatey.org/install#non-administrative-install for details.

For the question below, you have 20 seconds to make a selection.

 Do you want to continue?([Y]es/[N]o): y

Installing the following packages:
virtualbox
By installing you accept licenses for the packages.
Progress: Downloading virtualbox 6.0.6... 100%
virtualbox not installed. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\virtualbox' is denied.
virtualbox package files install completed. Performing other installation steps.
The install of virtualbox was NOT successful.
virtualbox not installed. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\virtualbox' is denied.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - virtualbox (exited 1) - virtualbox not installed. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\virtualbox' is denied.
PS C:\Users\MADHAN MOHAN REDDY>

**Comment by anon-42** [comment]
Seems like you are not running powershell as administrator, choco won't work without admin privilages.
Right click on powershell icon-> Run as administrator... Execute choco command

**Comment by ghost** [comment]
PowerShell run as admin
and install

**Comment by ghost** [comment]
if you have done close issue
