### ISSUE TITLE
I cant understand why i am getting as, failed= 1 on both the machines 

### ISSUE THREAD

**Issue by Rupini93** [QT-DevOps/AWSIssues#50]
![Screenshot (12)](https://user-images.githubusercontent.com/57709400/68992562-02e50680-0893-11ea-86e7-97c58d084cad.png)

**Comment by isaiah7p** [comment]
Step 1 : change permissions on s3 bucket - follow this url :  https://aws.amazon.com/premiumsupport/knowledge-center/read-access-objects-s3-bucket/ 
Step 2 : and try running 
wget https://s3-new-testing.s3.ap-south-1.amazonaws.com/info.php
