### ISSUE TITLE
Not able to open instance created through CLI

### ISSUE THREAD

**Issue by tejarajaboina** [QT-DevOps/AWSIssues#51]
I have launched an EC2 machine through (CLI User) CLI with default VPC and Subnet:

aws ec2 run-instances --count 1 --image-id ami-04b9e92b5572fa0d1 --instance-type t2.micro --key-name Ec2leaning --security-group-ids sg-bf723de5 --subnet-id subnet-37065e6b

I logged in Console with root account and copied :
ssh -i "Ec2leaning.pem" ubuntu@ec2-3-82-49-100.compute-1.amazonaws.com
from pem file path opened git and ran above command.

I am not able to connect receiving an error like 
ssh: connect to host ec2-3-82-49-100.compute-1.amazonaws.com port 22: Connection timed out

![image](https://user-images.githubusercontent.com/24681635/68992997-d633ed80-0898-11ea-833f-7a0723ab0955.png)

**Comment by srmanikanta** [comment]
please follow the below steps:
* your ec2ex.pem file is in downloads path
* check security group if ssh 22 is allow or not
* check the machine is running if it is running please take the correct ssh id
I hope this is useful to you if not please ignore
Note: if you run your machine with a default vpc noproblem but if you run your machine with custom vpc please check once your vpc is configured correctly or not
if you find the solution to this please close the issue

**Comment by Abbanapuri** [comment]
delete default vpc 
and create new default vpc
if you use default vpc
otherwise please check your vpc
