### ISSUE TITLE
apache webpage not opened on giving public ip-address

### ISSUE THREAD

**Issue by Jagannath92** [QT-DevOps/AWSIssues#52]
Following are the screen shoot of instance and security group. 
<img width="959" alt="1" src="https://user-images.githubusercontent.com/58015684/69294082-daf9f800-0c30-11ea-87c9-347d44160e58.PNG">
<img width="954" alt="4" src="https://user-images.githubusercontent.com/58015684/69314262-b8300980-0c59-11ea-918d-7395472c9c4e.PNG">

Same outbound rules as inbound rules of above screen shot
after creating ec2 instance install apache and lamp stack application successfully

**Comment by Jagannath92** [comment]
I have given same to outbound rules as type all traffic

**Comment by AnandSag** [comment]
We suppose to use public IP address of the machine to access Apache web page.

**Comment by Jagannath92** [comment]
I am facing same error on using public ip address
<img width="618" alt="5" src="https://user-images.githubusercontent.com/58015684/69389944-89ff0800-0cf3-11ea-8f67-0a4faad8eb70.PNG">

**Comment by srmanikanta** [comment]
please check the below things:
follow the step1 or step 2 according to your machine but finally follow the step3 
1.if you use ubuntu machine follow the below steps
* check the apache2 installed or not
#dpkg -l apache2
if you installed it will shown the package along with version
if not try
#sudo apt-get update
#sudo apt-get install apache2 -y
2. if you use redhat machine follow the below steps
* check the httpd installed or not
#rpm -q httpd
if you installed it will shown the package along with version
if not try 
#sudo yum update
#sudo yum install httpd -y
step 3:
http://<yourmachinepublicip:80>
Note: open  port 80 in security group.
I think it is useful to you if not please ignore
you did this already please close the issue.

**Comment by Jagannath92** [comment]
Issue solved, Thankyou for update
