### ISSUE TITLE
Data base connection issue

### ISSUE THREAD

**Issue by tejarajaboina** [QT-DevOps/AWSIssues#57]
![image](https://user-images.githubusercontent.com/24681635/70416675-9d48fc00-1a85-11ea-88fc-5cdccf13ed66.png)

![image](https://user-images.githubusercontent.com/24681635/70416727-b782da00-1a85-11ea-811e-afaaf44976a3.png)

I am not able to connect to DB
admin is user.
what would be issue here.

Thanks,
Teja

**Comment by tejarajaboina** [comment]
i made publicly accessible and tried but same error

**Comment by anupam-fl** [comment]
Hello tejarajaboina,
Please check if you have made the database public accessible. 

Secondly, can you check what type of inbound connections the vpc security group is accepting? 
Please click on the vpc group below to confirm. You may need to modify it to allow the inbound access.

![image](https://user-images.githubusercontent.com/58856475/70822925-b36bfa80-1dac-11ea-95a8-554cccb38687.png)

Thanks.

**Comment by tejarajaboina** [comment]
Thanks that helped

**Comment by tejarajaboina** [comment]
: )
