### ISSUE TITLE
Not able to connect EC2 Machine: Connection timed out

### ISSUE THREAD

**Issue by tejarajaboina** [QT-DevOps/AWSIssues#58]

**Comment by tejarajaboina** [comment]
please find attached screenshots
[timeout Error.pdf](https://github.com/QT-DevOps/AWSIssues/files/3968375/timeout.Error.pdf)

**Comment by vinodh2020** [comment]
Please check if Ec2 mechine is in Private VPC . Please make sure to use Public in VPC to access it from internet

**Comment by tejarajaboina** [comment]
No machine is in Public VPC only

**Comment by vinodh2020** [comment]
Please check Route table  for VPC  subnets, there you can get some clue to allow all Ip's

**Comment by anupam-fl** [comment]
Hello Teja,
To isolate the issue, could you try creating a new EC2 instance in another region, say US-West-2a. 
Please ensure that you setup a rule in your security group to allow all inbound traffic(for testing purpose).

Secondly, for the new instance, please create and download a new .pem file for connecting to the instance from your terminal.

Please let us know how it works.

Thanks.

**Comment by bschaitanya91** [comment]
Hi Anupam/Vinod,

We have given All Traffic in Security Groups, Network ACL.
We gave opte 10.0.0.0/16 in Route tables and 10.0.1.0/24 in subnets.
We Associated subnets to route tables.
And also associated VPC to respective subnets, NACL, Route Tables.
And we made public enabled while creating LINUX EC2 machine, associated respective security groups and created new key pair. 
We did all this in new AZ. Still it doesn't work.

**Comment by anupam-fl** [comment]
Hi,
Can you attach the screenshots of the EC2 creation and login steps? In EC2 creation, apart from setting up the security group to allow all traffic, please leave other settings such as route tables, etc as is, in default mode.

I’m basically asking you to use the steps mimicking the classroom scenario.

Thanks.

**Comment by bschaitanya91** [comment]
Hi 

I have attached whole EC2 Session creation. And Timeout Session error.
[EC2 Timeout Error.docx](https://github.com/QT-DevOps/AWSIssues/files/3991176/EC2.Timeout.Error.docx)

**Comment by anupam-fl** [comment]
Hello Sai,
Thank you for the screenshots.
 
It seems you are doing it in the Ohio AZ. Can you try it in the US-West-2a ? 
I had similar problems setting things up in Ohio AZ. Changing it to a different zone helped me.

Please try it and see how it works.

![image](https://user-images.githubusercontent.com/58856475/71311650-b8edc400-23ee-11ea-833e-b9e0dce15ba4.png)


Thanks.

**Comment by bschaitanya91** [comment]
Hi Anupam,

It worked in Oregon, Thanks. But may I know why it didn't work on other regions.

Regards,
Sai.

**Comment by anupam-fl** [comment]
Hello Sai,
It probably has something to do with new accounts but not completely sure. Can you try again creating an instance in the Ohio region? If it doesn't work, then you can contact AWS support for assistance. https://support.aws.amazon.com/#/contacts/aws-account-support

Thanks.

**Comment by ABBANAPURI0445** [comment]
please close issue teja

**Comment by tejarajaboina** [comment]
Thanks for your help
