### ISSUE TITLE
Unable to start printspooler in powershell

### ISSUE THREAD

**Issue by SrivatsaSrikakolapu** [QT-DevOps/AWSIssues#61]
This is regarding the class on 12-21-2019. I am unable to start the process printspooler, but I followed every step that was told. I am sharing the screenshots of the error that I got. Please clarify the mistake that I did.
![powershell4](https://user-images.githubusercontent.com/59303499/71539938-9ff28f00-2969-11ea-8fcc-883122b1b18b.png)

![powershell1](https://user-images.githubusercontent.com/59303499/71539879-12af3a80-2969-11ea-9e6b-fcfd27f545ac.png)
![powershell2](https://user-images.githubusercontent.com/59303499/71539880-12af3a80-2969-11ea-80b7-f319e45f5ee5.png)
![powershell3](https://user-images.githubusercontent.com/59303499/71539881-1347d100-2969-11ea-8066-ba793aecf2c5.png)

**Comment by anupam-fl** [comment]
Hello SrivatsaSrikakolapu,
Can you execute the command without the -force parameter? Before doing it, please ensure the 'print spooler' service is stopped.

Thanks.

**Comment by SrivatsaSrikakolapu** [comment]
Hi anupam,
If you see the screenshot, the spooler's service status is already "stopped". I have tried it without force ,it was not working and so I tried it with force later on. Even then its not working.

**Comment by anupam-fl** [comment]
Hi SrivatsaSrikakolapu,
To isolate the problem, can you create a new process, with a different name and see if it works.

Thanks.

**Comment by SrivatsaSrikakolapu** [comment]
Hello anupam,
I tried that too, but of no use.

**Comment by NareshAbbanapuri** [comment]
hi 
please try to fix manually if its works then look at DSC
