### ISSUE TITLE
VM import/export

### ISSUE THREAD

**Issue by pavankumarr3ddy** [QT-DevOps/AWSIssues#66]
![image](https://user-images.githubusercontent.com/58127643/73150773-047e4680-40ee-11ea-9a88-3dbe558b7db2.png)

**Comment by madhaviaws** [comment]
I am also facing same issue.

**Comment by MakrandakaMax** [comment]
I followed this [https://www.msp360.com/resources/blog/how-to-configure-vmimport-role/](url) and it works. But don't know if this is something that has to be done or not. (The link does not work when you click on it so just highllight it, copy it and paste it.)

**Comment by madhaviaws** [comment]
Thank you . It is working

**Comment by srmanikanta** [comment]
please add the required policy and roles for image import  
follow this link [click here ](https://docs.aws.amazon.com/vm-import/latest/userguide/vmimport-image-import.html)

once the above link is opend then  click on prerequisites--> click required service role
please read the documentation and add the required roles and policies.

**Comment by pavankumarr3ddy** [comment]
Still i'm getting the same error even after trying the documentation given by @srmanikanta . Could you please check this out again. 
![image](https://user-images.githubusercontent.com/58127643/73327527-56ed6d80-427c-11ea-9004-65d3433cc5b6.png)

**Comment by rakeshirukula** [comment]
didnt get it ?? still same problem .Can someone explain which link to follow ?

**Comment by pranganathp** [comment]
Still facing the same issue?. Then, its time to follow below thread to resolve the issue;
https://forums.aws.amazon.com/thread.jspa?threadID=179090

**Comment by Ahmed3k** [comment]
> please add the required policy and roles for image import
> follow this link [ckick here ](https://docs.aws.amazon.com/vm-import/latest/userguide/vmie_prereqs.html#vmimport-role)

Followed the link but still facing this same issue.

**Comment by pavankumarr3ddy** [comment]
I have checked with all the possibilities and all the permissions.. but still i sturcked at role-policy.. i have gone through all the documentation [here](https://docs.aws.amazon.com/vm-import/latest/userguide/vmie_prereqs.html#vmimport-role) . still i'm unable to get it.. could u please check once again.

![image](https://user-images.githubusercontent.com/58127643/73430741-cf2f5e00-4364-11ea-9096-70cd6aea7c34.png)

**Comment by srmanikanta** [comment]
please add the required policy and roles for image import
follow this link [click here]()

once the above link is opend then click on prerequisites--> click required service role
please read the documentation and add the required roles and policies.
