### ISSUE TITLE
Error comes while entering to remote desktop environment

### ISSUE THREAD

**Issue by abhisheknayak101** [QT-DevOps/AWSIssues#67]
i have created an ec2 machine with t2.xlarge size which contains 4 cpu & 32 gib of memory.
after that i got my password & download the remote desktop file.
But while entering to the remote desktop environment it shows the error.
![IMG_20200128_161729](https://user-images.githubusercontent.com/59557076/73258648-2a8a1080-41ec-11ea-9d8a-10655e8af651.jpg)

**Comment by srmanikanta** [comment]
t2 series is not supported for virtulization please take i3.metal for better understanding for this error 
abhisheknayak follow this link [click here](https://aws.amazon.com/blogs/compute/running-hyper-v-on-amazon-ec2-bare-metal-instances/)

**Comment by abhisheknayak101** [comment]
> please check your instance is running or not

Yes my instance was running then i created my password & after that downloaded the remote desktop file but after that when i tried to enter in that environment it shows the above error

**Comment by AmrishPopat** [comment]
My Windows Home Edition doesn't support Remote Desktop. Any one has a work around?

**Comment by guravareddy1234** [comment]
hi abhishek , when you create Windows_Server-2016-English-Full-Base-2020.02.12 - ami-0a017e6b84bbbca59 , when you enter security group please select type as RDP then you will get.
![HyperVRdp](https://user-images.githubusercontent.com/22844438/74950246-d5c16a80-5424-11ea-9aab-9b120fbeaf59.png)
