### ISSUE TITLE
error when executing the packer validate template

### ISSUE THREAD

**Issue by chowdamramana** [QT-DevOps/AWSIssues#7]
![error 1](https://user-images.githubusercontent.com/50665358/57843607-3499e980-77ec-11e9-9593-3a4a3da309f4.PNG)

**Comment by chowdamramana** [comment]
![error1](https://user-images.githubusercontent.com/50665358/57845681-1a620a80-77f0-11e9-8f10-e5ec56032d63.PNG)

**Comment by allinonedashboard** [comment]
remove the comma at the end of line 8 @chowdamramana

**Comment by chowdamramana** [comment]
![error 2](https://user-images.githubusercontent.com/50665358/57858815-5d7fa600-780f-11e9-87f8-92b19eeeac9d.PNG)
![error gen](https://user-images.githubusercontent.com/50665358/57858816-5d7fa600-780f-11e9-8fd7-1f7f60829d89.PNG)

**Comment by chowdamramana** [comment]
I am removing the comma but I still got an error

**Comment by allinonedashboard** [comment]
Now, the error is with the syntax @chowdamramana 
![image](https://user-images.githubusercontent.com/50626781/57868950-d70d9900-77fb-11e9-810c-090a343d1d76.png)
you miss to add ` at the end and try (line 16 & 17)
