### ISSUE TITLE
problem importing the image

### ISSUE THREAD

**Issue by vamsi0848** [QT-DevOps/AWSIssues#70]
![Screenshot (19)](https://user-images.githubusercontent.com/57513633/73425108-a1431d00-4356-11ea-8f8f-0945432fa14d.png)

**Comment by vamsi0848** [comment]
It's showing like this

...
An error occurred (InvalidParameter) when calling the ImportImage operation: The service role <vmimport> does not exist or does not have sufficient permissions for the service to continue
...

**Comment by ABBANAPURI0445** [comment]
please check #66 issue

**Comment by srmanikanta** [comment]
please add the required policy and roles for image import
follow this link ckick here

once the above link is opend then click on prerequisites--> click required service role
please read the documentation and add the required roles and policies.
