### ISSUE TITLE
Error While creating Cloud Formation

### ISSUE THREAD

**Issue by bschaitanya91** [QT-DevOps/AWSIssues#71]
Tried to create CF with attached Jason script, which is throwing error as "Unexpected value(s) found: [Name]", "The following resource(s) failed to create: [NewLearning]. . Rollback requested by user." And then it is doing rollback. Please check screenshots and do needful.
![Cflearning_error](https://user-images.githubusercontent.com/41133733/73446619-13c9f200-4383-11ea-9db9-b904eab4eb3a.PNG)
[vpcCF.txt](https://github.com/QT-DevOps/AWSIssues/files/4133792/vpcCF.txt)

**Comment by ABBANAPURI0445** [comment]
{
    "AWSTemplateFormatVersion" : "2010-09-09",
    "Description" : "trying to create sample arch",
"Resources" : {
       
       "name": {
         "Type": "AWS::EC2::VPC",
         "Properties": {
           "CidrBlock": "192.168.0.0/16",
          
         }
       }
       

    }
}
