### ISSUE TITLE
AMI Export issue

### ISSUE THREAD

**Issue by Rajkumar-Aute** [QT-DevOps/AWSIssues#72]
I am using this command to export the AMI to S3.
'''
aws ec2 export-image --image-id ami-xxxxxxxxxxxxxxxxx --disk-image-format VMDK --s3-export-location S3Bucket=xxxxbackup,S3Prefix=exports/
'''
I am getting error while exporting.
'''
An error occurred (InvalidParameter) when calling the ExportImage operation: The service role vmimport provided does not exist or does not have sufficient permissions
'''
Kindly help to solve this issue

**Comment by shaikkhajaibrahim** [comment]
Refer to issue #66

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
