### ISSUE TITLE
Unable to copy pem file to ec2

### ISSUE THREAD

**Issue by sumanbehera** [QT-DevOps/AWSIssues#75]
Hi I am using below scp command and endedup in lost connection error.
scp -i test.pem ./test.pem ec2-user@<publicip>:/home/ec2-user/

Warning: Identity file test.pem not accessible: No such file or directory.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
lost connection

**Comment by srmanikanta** [comment]
follow this syntax:
```
scp -i <your pem file> <sourcefile>  <destinationserveuser>@<publicip>:<homedirectory/path>
```
* Example:
`scp -i ./test.pem test.pem ec2-user@<publicip>:/home/ec2-user`
