### ISSUE TITLE
access denied to push repository to github

### ISSUE THREAD

**Issue by avinashbattu** [QT-DevOps/AWSIssues#76]
![avi](https://user-images.githubusercontent.com/53613232/75175137-c8bfb680-5757-11ea-9073-bc704480c2ae.png)
git remote add origin git@github.com:avinashbattu/gitpractiserepo-ecommerce.git

i am trying to add git remote add origin it is showing error 403 and it is telling file already exist
please tell me the solution

**Comment by srmanikanta** [comment]
please check these things:
* check your git repo from local as well as remote
* check your git repo is added or not 
* currently you are trying to push the same repository path or not.
