### ISSUE TITLE
Issues while doing aws migration from hyper-v

### ISSUE THREAD

**Issue by Neelimapayasamgit** [QT-DevOps/AWSIssues#77]
1. Even though I am giving correct management console password getting this error 
![image](https://user-images.githubusercontent.com/58906215/75373590-7c44ba00-58c2-11ea-9b76-14c3e3ace22c.png)

2. is there any way to copy paste commands to hyper-v guest vms (for example i want to create mysql db in our one of the gues VM database , but copy pste is not working from hyper-v host to guest in all 3 vms)

Please help.

**Comment by srmanikanta** [comment]
* Install gitbash on host machine and the use scp command .
The syntax look like this
`scp <sourcefile> <destination>`
For example;
`scp  test.txt destinationuser@destinationvmip:/home/user `
if this is helpful to you please close the issue.
