### ISSUE TITLE
issue while VM import

### ISSUE THREAD

**Issue by tejarajaboina** [QT-DevOps/AWSIssues#79]
HI Team,

error : An error occurred (InvalidParameter) when calling the ImportImage operation: The service role <vmimport> does not exist or does not have sufficient permissions for the service to continue

IAM USER: 
Permissions:AdministratorAccess, VMImportExportRoleForAWSConnector

bucket : 
access:Objects can be public

what would be the reason for error.

Thanks,
Teja

**Comment by srmanikanta** [comment]
please add the required policy and roles for image import  
follow this link [click here ](https://docs.aws.amazon.com/vm-import/latest/userguide/vmimport-image-import.html)

once the above link is opend then  click on prerequisites--> click required service role
please read the documentation and add the required roles and policies.
