### ISSUE TITLE
when i create a image with packer i got a error when executing the build-debug comand

### ISSUE THREAD

**Issue by chowdamramana** [QT-DevOps/AWSIssues#8]

**Comment by chowdamramana** [comment]
![build error](https://user-images.githubusercontent.com/50665358/57874126-831ba800-782d-11e9-997d-2b0017f71fd4.PNG)
![packer image creation](https://user-images.githubusercontent.com/50665358/57874127-831ba800-782d-11e9-82c1-88455cfce7e2.PNG)

**Comment by allinonedashboard** [comment]
User doesn't have privileged access to do this operation. Please grant access to the user and give a try.
Hope below steps will help you
1) visit https://console.aws.amazon.com/iam/home
2) select policies in the left-hand menu
3) create administrator policy from amazons existing policies
4) select administrator checkbox and attach to your user

**Comment by chowdamramana** [comment]
I am done those steps but still, I got an error
![error build 2](https://user-images.githubusercontent.com/50665358/57918018-92453900-78b3-11e9-89d9-ba81589f4378.PNG)
.

**Comment by ghost** [comment]
give different packer name
