### ISSUE TITLE
Can't select a VM size in Azure Account: Grayed out.

### ISSUE THREAD

**Issue by vineethnnn** [QT-DevOps/AWSIssues#80]
Hi Team,

   Tried creating a VM in my Azure account but i'm unable to select VM Size as all the VM's are grayed out.

Please help out with this issue, I have attached screenshot for your reference..

![AZ-VM Error](https://user-images.githubusercontent.com/61907776/77777315-68cd7000-7075-11ea-97a8-3a58a86fd574.PNG)

**Comment by rakesh741** [comment]
hii,
 vineeth i hav a same issue. can any one solve this whats the issue.

**Comment by srmanikanta** [comment]
clear all the filters in the search bar and check the subscription.

**Comment by NareshAbbanapuri** [comment]
issue with azure 
please upgrade your account to pay as you go
and you will get free credits

**Comment by shaikkhajaibrahim** [comment]
Please raise that in azure issues
