### ISSUE TITLE
S3, BUCKET POLICIES  NOT  CLEAR

### ISSUE THREAD

**Issue by Mohan007177** [QT-DevOps/AWSIssues#81]
QT  TEANM

PL. share  S3  bucket  polices  best pratices

+
go  depper in AWS  RESOURCES+DEVOPS  REMAING SYLLBUSA

MOHAN

**Comment by srmanikanta** [comment]
refer github, in github lot of examples is there  and also read the  aws documentation for best practices.

**Comment by Mohan007177** [comment]
Please  

Share  the  doc's  &  gitub  URLS'S   Sepicifcally

**Comment by Mohan007177** [comment]
Major  diff  IAM POLICE   VS  S3  BUCKET  POLICES  I  NEED  10  EXAMPLESE

**Comment by shaikkhajaibrahim** [comment]
Mohan I expect this is something which you can search for your self. This issues page is for practical problems. Refrain from design discussion. For that you have to schedule meeting with me
