### ISSUE TITLE
Can  any  one  clarify  on  this  issues ENDPOINT , ENDPOINT SERVICES  IN AWS

### ISSUE THREAD

**Issue by Mohan007177** [QT-DevOps/AWSIssues#83]
END POINT GATEWAY
ENDPOINT INTERFACES
ENDPOINT SERVICES

**Comment by srmanikanta** [comment]
A VPC endpoint enables you to privately connect your VPC to supported AWS services and VPC endpoint services powered by AWS PrivateLink without requiring an internet gateway, NAT device, VPN connection, or AWS Direct Connect connection.

vpc endpoints  are two types 

1. interface endpint:

An interface endpoint is an elastic network interface with a private IP address from the IP address range of your subnet that serves as an entry point for traffic destined to a supported service.

supported services are: ec2,api gateway,cloud watch,cloud formation,sqs,sns,code build,code commit,code pipeline vice versa. 
 
2. gateway endpoint:

A gateway endpoint is a gateway that you specify as a target for a route in your route table for traffic destined to a supported AWS service. 

 supported services are: s3, dynamodb.

[click here](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html) for vpc endpoints reference 


Endpoint:

To connect programmatically to an AWS service, you use an endpoint. An endpoint is the URL of the entry point for an AWS web service. The AWS SDKs and the AWS Command Line Interface (AWS CLI) automatically use the default endpoint for each service in an AWS Region. But you can specify an alternate endpoint for your API requests.

endpoints are:
Regional Endpoints
Service Endpoints
FIPS Endpoints

[click here](https://docs.aws.amazon.com/general/latest/gr/rande.html) for endpoint reference.

**Comment by Mohan007177** [comment]
Thanks  i  will  gothou  that

**Comment by shaikkhajaibrahim** [comment]
Mohan I expect this is something which you can search for your self. This issues page is for practical problems. Refrain from design discussion. For that you have to schedule meeting with me
