### ISSUE TITLE
Level 200: Automated Deployment of VPC

### ISSUE THREAD

**Issue by Mohan007177** [QT-DevOps/AWSIssues#84]
VPC security features
VPC layered subnet architecture
Automated deployments

**Comment by srmanikanta** [comment]
please read the aws documentation everything will be there

**Comment by Mohan007177** [comment]
Pl. Share  list  Doc's  

ASAP

**Comment by Mohan007177** [comment]
Pl. Share list Doc's

ASAP

**Comment by NareshAbbanapuri** [comment]
security groups:
------------------
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-security-groups.html

NACL:
--------
https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html

**Comment by shaikkhajaibrahim** [comment]
Mohan I expect this is something which you can search for your self. This issues page is for practical problems. Refrain from design discussion. For that you have to schedule meeting with me
