### ISSUE TITLE
ssh permission denied issue

### ISSUE THREAD

**Issue by Jagannath92** [QT-DevOps/AWSIssues#85]
![Capture](https://user-images.githubusercontent.com/58015684/78417925-d7519580-7654-11ea-814d-9979885cecb7.PNG)
Unable to login from one machine to another machine. 
Could you please check it. Thanks

**Comment by NareshAbbanapuri** [comment]
hi Jagannath
please follow this steps
---
cd ~
ssh jenkins@ip
----

**Comment by srmanikanta** [comment]
hi jagannath 
Right now you are in root user home directory that is /root other than root any user doesn't have permissions to do anything over here
so before execute this command  `ssh  -i <your pem file path>  jenkins@18.191.230.61` simply type cd ~
then  `ssh -i <your pem key> jenkins@18.191.230.61`
please close the issue.

**Comment by rpkoya** [comment]
Hi Jagannath,
In AWS when ever you want to login to a machine, you need to provide the Key Pair, which you have downloaded during Launching of Instances, So, please give the command as below to conect to the machine.
 ssh -i <path to key> user@ipaddress

**Comment by rpkoya** [comment]
ssh -i <path to your key> user@ipaddress
This will connect to your machine, please check this and let me know.
