### ISSUE TITLE
Not Able to Communicate within a Same VPC Using custom Hostname

### ISSUE THREAD

**Issue by mayanksharma2080** [QT-DevOps/AWSIssues#86]
Hi,
I have create 2 EC2 Instances in a VPC and enabled DNS resolution and DNS Hostname resolution and changed hostnames of both machines as Example1 and Example2 but i am not able to ping each other using custom.

**Comment by shaikkhajaibrahim** [comment]
Share your NACL AND SECURITY GROUP

**Comment by mayanksharma2080** [comment]
Thanks for reverting back sir, Hope your health is better now.
I have allowed all traffic in SG and NACL.

![SG](https://user-images.githubusercontent.com/44578980/79525241-0c5fde00-8080-11ea-9731-e4261449ad51.PNG)
![NACL](https://user-images.githubusercontent.com/44578980/79525267-171a7300-8080-11ea-9a94-3116f0755870.PNG)

**Comment by mayanksharma2080** [comment]
I am able to ping these instances using IPs but not able to ping using Custom hostnames.

![image](https://user-images.githubusercontent.com/44578980/79527068-521ea580-8084-11ea-9640-191af6c08f6e.png)

![image](https://user-images.githubusercontent.com/44578980/79527137-767a8200-8084-11ea-973b-b6b167052989.png)

**Comment by NareshAbbanapuri** [comment]
hi
we can able to ping DNS or Ip 
machine name I don't think so

**Comment by shaikkhajaibrahim** [comment]
![image](https://user-images.githubusercontent.com/2438317/79633092-deae8e00-8180-11ea-92d5-482ac3285d02.png)

Refer https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html
