### ISSUE TITLE
couldn't connecting to endpoint url

### ISSUE THREAD

**Issue by manasa373767** [QT-DevOps/AWSIssues#87]
![24](https://user-images.githubusercontent.com/62063357/79559745-ec520e00-80c3-11ea-8a14-7e0f44e72396.png)

**Comment by NareshAbbanapuri** [comment]
hi manasa
region is us-east-1 
us-east-1a means availabilty zone
please remove a

**Comment by manasa373767** [comment]
yes its working...
Is that region works for default or it should be always particular?

**Comment by srmanikanta** [comment]
us-east-1 is default region for aws cli if you want you can change at any point.

**Comment by manasa373767** [comment]
ok..thanks for the information
