### ISSUE TITLE
I'm unable to view Info.php in Auto Scaling Instance

### ISSUE THREAD

**Issue by vineethnnn** [QT-DevOps/AWSIssues#88]
Created a auto scaling group but i'm unable to view info.php page if i give public IP address of ec2 machine which i created using auto scaling.

But if i give the public IP address of the normal ec2 ubentu machine where i have executed the below commands

sudo apt-get update
sudo apt-get install apache2 -y
sudo apt install php libapache2-mod-php php-mysql -y
sudo systemctl restart apache2
sudo systemctl enable apache2
sudo apt install php-cli -y
sudo vi /var/www/html/info.php => 
<?php
phpinfo();
?>
sudo systemctl restart apache2
sudo apt-get install stress -y

I'm able to see the info.php page getting displayed.

Kindly look into this issue

**Comment by NareshAbbanapuri** [comment]
open file /var/www/html/info.php and enter php code 
enable 80 port in security group
access page 
---
publicip:80/info.php
---

**Comment by vineethnnn** [comment]
Can you please explain clearly what are the steps needs to be done?

**Comment by srmanikanta** [comment]
connect to your instance 
change as root. execute the below commands
```
sudo -i 
vi /var/www/html/info.php
```
copy the below content in your info.php file 
```
<?php
phpinfo();
?>
```
once copied then save the file (like esc ,shift+:, wq)
restart your apache server 
```
sudo systemctl restart apache2
```
create ami again.

configure you autoscalling right now.

**Comment by NareshAbbanapuri** [comment]
Hi vineeth 
please close the issue if resolved

**Comment by vineethnnn** [comment]
Done it has been closed
