### ISSUE TITLE
MYSQL WORKBENCH NOT RESPONDING WHEN TRYING TO SET UP CONNECTION WITH AWS RDS

### ISSUE THREAD

**Issue by SURESHREDDY645102** [QT-DevOps/AWSIssues#90]
I tried to setup new connection BTW aws mysql rds and mysql workbench. After entering the end point I tried to test connection it shows not responding. Can anyone please solve this issue. Thank you!

**Comment by srmanikanta** [comment]
check the security group of mysql.
