### ISSUE TITLE
Error while trying to create a ec2 instance using Auto scaling group

### ISSUE THREAD

**Issue by madhaviaws** [QT-DevOps/AWSIssues#91]
Hi, 

I have created a Launch configuration using the below cloud formation template and created Autoscaling group using AWS Console. I am getting the below error while launching Ec2 instance using Auto scaling group.Please find the screen shots.

Error:

Launching a new EC2 instance. Status Reason: The parameter groupName cannot be used with the parameter subnet. Launching EC2 instance failed.
--
Cause:CauseAt 2020-04-29T07:46:29Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 1.

Script:
[ASG Error.docx](https://github.com/QT-DevOps/AWSIssues/files/4550359/ASG.Error.docx)

{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "Exercise-1: Launch configuation",
    "Parameters": {
        "keyvaluepair": {
            "Description": "Key value pair",
            "Type": "AWS::EC2::KeyPair::KeyName"
        },
        "securitygroup": {
            "Description": "Security group name",
            "Type": "AWS::EC2::SecurityGroup::GroupName"
        }
    },
    "Resources": {
        "myLaunchConfig": {
            "Type": "AWS::AutoScaling::LaunchConfiguration",
            "Properties": {
                "KeyName": {
                    "Ref": "keyvaluepair"
                },
                "SecurityGroups": [
                    {
                        "Ref": "securitygroup"
                    }
                ],
                "ImageId": "ami-071ef7270bf52835d",
                "InstanceType": "t2.micro"
            }
        }
    }
}

**Comment by srmanikanta** [comment]
if it is aws challenge please try to resolve the error by yourself  do not post those challenges over here because it is a challenge so try to find the solution with your own in case if you are not find the solution then wait for the next challenge and ask over here then i will post the solution here.

please try to find the solutions for challenges with your own.

if you have any classroom doubts please ask over here.
