### ISSUE TITLE
Unable to delete system snapshot either when DB instance is active or Deleted

### ISSUE THREAD

**Issue by sekharreddy0584** [QT-DevOps/AWSIssues#92]
Hi Sir,

I am unable to delete system snapshots either when DB instance is active or Deleted.
I tried by modified Backup retention to zero, but no luck.

Please help on it.

Thanks.
[Snapshot.pdf](https://github.com/QT-DevOps/AWSIssues/files/4556494/Snapshot.pdf)

**Comment by srmanikanta** [comment]
please read this document and delete the snapshots [Click Here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_DeleteSnapshot.html)

**Comment by sekharreddy0584** [comment]
Thanks for your support.
