### ISSUE TITLE
unable to ssh ec2 instance

### ISSUE THREAD

**Issue by sudhup** [QT-DevOps/AWSIssues#93]
Hi I'm trying to ssh to my ubuntu ec2 instance.

I'm getting the following error
**Network error: Connection timed out**

My security group inbound rules are allowed for public (ssh, http, 8080)

I can access jenkins from the same server via port 8080

**Comment by srmanikanta** [comment]
use this command to check the network connection `ping <publicip>`
if  your network is slow then you have loss some packets. 
if you don't have packet loss then check the security group.
still the issue is not resolved please post a screenshot of your ping command and security group,
