### ISSUE TITLE
Could any of you help me in connecting AWS EC2 instance using Visual Studio code

### ISSUE THREAD

**Issue by Ahmed3k** [QT-DevOps/AWSIssues#95]
I am trying to remote ssh into the AWS EC2 instance created a config file as well but unable to connect 

could you any off you help me with this.

Thank you

**Comment by srmanikanta** [comment]
follow this procedure:
* launch an ec2 machine in aws 
* at the time lacunch ec2 machine it will ask for download a private key
* the downloaded private key is stored in your downloads of your windows system
* then open a git bash over here 
* goto your aws ec2 machine and select which machine you want to connect then click on connect 
and copy the ssh command( In the below there is a line start with example then copy the below ssh commad) 
* once copied that command then goto your git bash paste it 
*  it asks yes/no prompt you have to enter yes
* finally it connected

The above procedure is for connecting a ec2 machine. I hope you are asking this one but config file is not required for this procedure( remote ssh).

**Comment by Ahmed3k** [comment]
![Remote SSH](https://user-images.githubusercontent.com/60425789/81139964-57855680-8f85-11ea-9b87-caf4545fca4c.jpeg)

**Comment by Ahmed3k** [comment]
Gitbash is oneway of connecting but could you assist me connecting through Visual studio code

**Comment by SURESHREDDY645102** [comment]
You can create IAM user and try login using Access Key and Secret Access key from Visual studio code.

**Comment by srmanikanta** [comment]
if you use visual studio code for remote ssh install power shell extension. once you installed the power shell extension then click on power shell icon 
`ssh -i <prmfile> usernmae@ip`  if you have a password then `ssh username@ip` but this time it will ask password enter your password.

if you install remote-ssh extension please read this document and go through that [Click Here](https://code.visualstudio.com/docs/remote/ssh#_getting-started)

I think this is useful to you if not please ignore.

**Comment by shaikkhajaibrahim** [comment]
Is this done
