### ISSUE TITLE
Connection timeout issue with EC2 machine

### ISSUE THREAD

**Issue by kirandevops12** [QT-DevOps/AWSIssues#96]
I am facing an issue that if I leave my EC2 machine idle for more than 2 minutes, I am loosing the ssh connection and getting the error message '**client_loop: send disconnect: Connection reset by peer'.**

I have to again connect to the machine to continue machine. I have tried the below options to resolve the issue but the issue still remains the same.
1. Restarting the EC2 machine
2. Followed the instruction mentioned in the below link
https://brakertech.com/ssh-keeps-disconnecting/

Please help.

**Comment by srmanikanta** [comment]
please check the security group and enable all traffic.

**Comment by kirandevops12** [comment]
Hi manikanta,

All traffic is already enabled.
Please see the inbound and outbound rules of my security group below. Let me know if I am missing anything.

![image](https://user-images.githubusercontent.com/64950146/81466881-8c4a1580-91f2-11ea-9aea-2f68e3f037e5.png)

![image](https://user-images.githubusercontent.com/64950146/81466905-b0a5f200-91f2-11ea-9611-bf87e82c43db.png)

**Comment by srmanikanta** [comment]
check the network connectivity 
`ping <publicip>`
if packet are sending your network connection is good otherwise it says packer lose error because your network problem. first check these things and then tell me.

**Comment by kirandevops12** [comment]
The connectivity is looking good.

![image](https://user-images.githubusercontent.com/64950146/81473394-c11e9280-921b-11ea-85f2-306e2a5ade36.png)

**Comment by srmanikanta** [comment]
Now go to your pem file path then right click open git bash then try to use ssh command for connectivity.

**Comment by kirandevops12** [comment]
This is not useful. Issue is still the same. Closing the issue.

**Comment by ghost** [comment]
I am also facing the same issue getting the error message 'client_loop: send disconnect: Connection reset by peer'.
