### ISSUE TITLE
Unable to describe instance status

### ISSUE THREAD

**Issue by vineethnnn** [QT-DevOps/AWSIssues#97]
Created a EC2 instance & executed the this command 

aws ec2 describe-instance-status --instance-id i-0818bdfc819ea8731

But I'm getting this error message as  

An error occurred (InvalidInstanceID.NotFound) when calling the DescribeInstanceStatus operation: The instance ID 'i-0818bdfc819ea8731' does not exist

![Capture1](https://user-images.githubusercontent.com/61907776/81479496-3c466f80-9241-11ea-9486-124677c7b5ad.PNG)

**Comment by srmanikanta** [comment]
follow these steps:
1.In aws go to iam service create a iam user with programetic access, attach admin permissions and download the accesskey and secret key file like download.csv.
2. install aws cli [Refer Here](https://docs.aws.amazon.com/cli/latest/userguide/install-windows.html)
3. configure cli `aws configure`
 provide access key, secret key, region,and output format json.
Now execute your aws commands.
