### ISSUE TITLE
Unable to upload Json Template in cloud formation

### ISSUE THREAD

**Issue by vineethnnn** [QT-DevOps/AWSIssues#98]
I created the below template when i tried to upload the below template.

{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "This template is created for learning and it create vpc with four subnets",
    "Resources": {
        "myvpc": {
            "Type": "AWS::EC2::VPC",
            "Properties": {
                "CidrBlock": "10.0.0.0/16",
                "EnableDnsHostnames": "true",
                "Tags": [
                    {
                        "Key": "Name",
                        "Value": "myvpc"
                    }
                ]
            }
        },
        "subnet1": {
            "Type": "AWS::EC2::Subnet",
            "Properties": {
                "VpcId": {
                    "Ref": "myvpc"
                },
                "CidrBlock": "10.0.0.0/24",
                "Tags": [
                    {
                        "Key": "Name",
                        "Value": "subnet1"
                    }
                ]
            }
        },
        "subnet2": {
            "Type": "AWS::EC2::Subnet",
            "Properties": {
                "VpcId": {
                    "Ref": "myvpc"
                },
                "CidrBlock": "10.0.1.0/24",
                "Tags": [
                    {
                        "Key": "Name",
                        "Value": "subnet2"
                    }
                ]
            }
        },
        "subnet3": {
            "Type": "AWS::EC2::Subnet",
            "Properties": {
                "VpcId": {
                    "Ref": "myvpc"
                },
                "CidrBlock": "10.0.2.0/24",
                "Tags": [
                    {
                        "Key": "Name",
                        "Value": "subnet3"
                    }
                ]
            }
        },
        "subnet4": {
            "Type": "AWS::EC2::Subnet",
            "Properties": {
                "VpcId": {
                    "Ref": "myvpc"
                },
                "CidrBlock": "10.0.3.0/24",
                "Tags": [
                    {
                        "Key": "Name",
                        "Value": "subnet4"
                    }
                ]
            }
        }
    }
}

I'm getting this error.

S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

**Comment by ramjagadeeshkumar** [comment]
your json file is working just click on 


{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "This template is created for learning and it create vpc with four subnets",
    "Resources": {
        "myvpc": {
            "Type": "AWS::EC2::VPC",
            "Properties": {
                "CidrBlock": "10.0.0.0/16",
                "EnableDnsHostnames": "true",
                "Tags": [
                    {
                        "Key": "Name",
                        "Value": "myvpc"
                    }
                ]
            }
        },
        "subnet1": {
            "Type": "AWS::EC2::Subnet",
            "Properties": {
                "VpcId": {
                    "Ref": "myvpc"
                },
                "CidrBlock": "10.0.0.0/24",
                "Tags": [
                    {
                        "Key": "Name",
                        "Value": "subnet1"
                    }
                ]
            }
        },
        "subnet2": {
            "Type": "AWS::EC2::Subnet",
            "Properties": {
                "VpcId": {
                    "Ref": "myvpc"
                },
                "CidrBlock": "10.0.1.0/24",
                "Tags": [
                    {
                        "Key": "Name",
                        "Value": "subnet2"
                    }
                ]
            }
        },
        "subnet3": {
            "Type": "AWS::EC2::Subnet",
            "Properties": {
                "VpcId": {
                    "Ref": "myvpc"
                },
                "CidrBlock": "10.0.2.0/24",
                "Tags": [
                    {
                        "Key": "Name",
                        "Value": "subnet3"
                    }
                ]
            }
        },
        "subnet4": {
            "Type": "AWS::EC2::Subnet",
            "Properties": {
                "VpcId": {
                    "Ref": "myvpc"
                },
                "CidrBlock": "10.0.3.0/24",
                "Tags": [
                    {
                        "Key": "Name",
                        "Value": "subnet4"
                    }
                ]
            }
        }
    }
}



format the document in json is working

**Comment by ramjagadeeshkumar** [comment]
open in visualstudio code and select all  format the document 

 your template is working 

![Screenshot (16)](https://user-images.githubusercontent.com/48975419/82724905-e79dfc80-9cf6-11ea-931d-3243b2aa8fc1.png)

**Comment by vineethnnn** [comment]
Formatted the document in visual studio still the same issue persists, Can you please look into this

**Comment by vineethnnn** [comment]
When i upload the Json template the below templates are created in S3.  i have attached the screenshot for your reference.


![S3issue](https://user-images.githubusercontent.com/61907776/82727043-96e1d000-9d05-11ea-9c8f-8527b00b634b.PNG)

**Comment by vineethnnn** [comment]
Viewed it in designer i got the below error message.

![s3 error acess](https://user-images.githubusercontent.com/61907776/82727148-55055980-9d06-11ea-815c-befc7c6003cd.PNG)

**Comment by ramjagadeeshkumar** [comment]
open your in vscode and select all right click mouse 
And formation the document it will arrange order in JSON format and save it  

Then upload the file to S3 buck and try it 
Your script is working for me 

If your getting same issue call to 8008017131

**Comment by vineethnnn** [comment]
H,
I'm still facing the same issue, Tried reaching you to this number : 8008017131.
But you didn't answer my call.

**Comment by vineethnnn** [comment]
H,

I'm still facing the same issue, Tried reaching you to this number :
8008017131.

But you didn't answer my call.

**Comment by ramjagadeeshkumar** [comment]
ok bro your issue is resloved

while update template need to save it  or put on autosave mode

please close issue if  resloved
